const units2 = [ 
   { 
       name: "gurei-oni", 
       faction:  "einar", 
       species:  "ogre", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "guard", 
       personality:  "tormenting", 
       size1:  "large", 
       size2:  7, 
       life:  4, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "sujoah", 
       faction:  "aquilla", 
       species:  "insect", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "predator", 
       personality:  "relentless", 
       size1:  "huge", 
       size2:  6, 
       life:  6, 
       move:  8, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  185,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "wo-sa-ga", 
       faction:  "utgar", 
       species:  "marro", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "hivelord", 
       personality:  "terrifying", 
       size1:  "huge", 
       size2:  10, 
       life:  4, 
       move:  6, 
       range:  1, 
       attack:  6, 
       defense:  4, 
       cost:  135,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
	   name: "zelrig", 
       faction:  "einar", 
       species:  "dragon", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "emperor", 
       personality:  "disciplined", 
       size1:  "huge", 
       size2:  11, 
       life:  6, 
       move:  6, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  185,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "zetacron", 
       faction:  "jandar", 
       species:  "soulborg", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "scout", 
       personality:  "precise", 
       size1:  "large", 
       size2:  7, 
       life:  2, 
       move:  5, 
       range:  8, 
       attack:  2, 
       defense:  4, 
       cost:  60,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "ana karithon", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "cleric", 
       personality:  "merciful", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  4, 
       attack:  2, 
       defense:  3, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "darrak ambershard", 
       faction:  "aquilla", 
       species:  "dwarf", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "rogue", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  4, 
       life:  4, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  2, 
       cost:  60,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "deepwyrm drow", 
       faction:  "utgar", 
       species:  "drow", 
       type1:  "common", 
       type2:  "squad", 
       class:  "warriors", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  70,
       MaxNoOfFigs: -1, 
       NoOfFigs: 1
   }, 
   { 
       name: "erevan sunshadow", 
       faction:  "jandar", 
       species:  "eladrin", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "wizard", 
       personality:  "precise", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  6, 
       range:  1, 
       attack:  2, 
       defense:  2, 
       cost:  80,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "feral troll", 
       faction:  "utgar", 
       species:  "troll", 
       type1:  "uncommon", 
       type2:  "hero", 
       class:  "hunter", 
       personality:  "ferocious", 
       size1:  "large", 
       size2:  7, 
       life:  8, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  1, 
       cost:  90,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "othkurik the black dragon", 
       faction:  "utgar", 
       species:  "dragon", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "young", 
       personality:  "tricky", 
       size1:  "large", 
       size2:  6, 
       life:  5, 
       move:  6, 
       range:  1, 
       attack:  4, 
       defense:  3, 
       cost:  140,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "pelloth", 
       faction:  "utgar", 
       species:  "drow", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "arachnomancer", 
       personality:  "devout", 
       size1:  "medium", 
       size2:  5, 
       life:  4, 
       move:  6, 
       range:  5, 
       attack:  3, 
       defense:  3, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "tandros kreel", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "fighter", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  7, 
       move:  5, 
       range:  5, 
       attack:  2, 
       defense:  4, 
       cost:  120,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "atlaga the kyrie warrior", 
       faction:  "ullar", 
       species:  "kyrie", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warrior", 
       personality:  "confident", 
       size1:  "medium", 
       size2:  6, 
       life:  4, 
       move:  5, 
       range:  5, 
       attack:  4, 
       defense:  3, 
       cost:  90,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "the axegrinders of burning forge", 
       faction:  "aquilla", 
       species:  "dwarf", 
       type1:  "common", 
       type2:  "squad", 
       class:  "fighters", 
       personality:  "fearless", 
       size1:  "small", 
       size2:  3, 
       life:  1, 
       move:  4, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  70,
       MaxNoOfFigs: -1, 
       NoOfFigs: 4
   }, 
   { 
       name: "brave arrow", 
       faction:  "aquilla", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "tribesman", 
       personality:  "fearsome", 
       size1:  "medium", 
       size2:  5, 
       life:  4, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  3, 
       cost:  50,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "capuan gladiators", 
       faction:  "einar", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "gladiators", 
       personality:  "rebellious", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  70,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "kumiko", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "ninja", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  4, 
       life:  3, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  5, 
       cost:  80,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "marro dividers", 
       faction:  "utgar", 
       species:  "marro", 
       type1:  "common", 
       type2:  "squad", 
       class:  "dividers", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  50,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "migol ironwill", 
       faction:  "aquilla", 
       species:  "dwarf", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "leader", 
       personality:  "resolute", 
       size1:  "small", 
       size2:  3, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  2, 
       defense:  4, 
       cost:  110,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "mohican river tribe", 
       faction:  "aquilla", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "scouts", 
       personality:  "fearsome", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  6, 
       attack:  2, 
       defense:  1, 
       cost:  70,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "protectors of ullar", 
       faction:  "ullar", 
       species:  "kyrie", 
       type1:  "common", 
       type2:  "squad", 
       class:  "protectors", 
       personality:  "confident", 
       size1:  "medium", 
       size2:  6, 
       life:  1, 
       move:  4, 
       range:  5, 
       attack:  3, 
       defense:  3, 
       cost:  110,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "omnicron repulsors", 
       faction:  "jandar", 
       species:  "soulborg", 
       type1:  "common", 
       type2:  "squad", 
       class:  "repulsors", 
       personality:  "precise", 
       size1:  "small", 
       size2:  3, 
       life:  1, 
       move:  5, 
       range:  7, 
       attack:  1, 
       defense:  3, 
       cost:  40,
       MaxNoOfFigs: -1, 
       NoOfFigs: 2
   }, 
   { 
       name: "tul-bak-ra", 
       faction:  "utgar", 
       species:  "marro", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "overlord", 
       personality:  "terrifying", 
       size1:  "medium", 
       size2:  5, 
       life:  6, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  130,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "air elemental", 
       faction:  "jandar", 
       species:  "elemental", 
       type1:  "common", 
       type2:  "hero", 
       class:  "construct", 
       personality:  "relentless", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  30,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "brandis skyhunter", 
       faction:  "ullar", 
       species:  "half-elf", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "ranger", 
       personality:  "precise", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  6, 
       range:  5, 
       attack:  3, 
       defense:  3, 
       cost:  90,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "drow chainfighter", 
       faction:  "utgar", 
       species:  "drow", 
       type1:  "common", 
       type2:  "hero", 
       class:  "guard", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  25,
       MaxNoOfFigs: -1, 
       NoOfFigs: 1
   }, 
   { 
       name: "earth elemental", 
       faction:  "einar", 
       species:  "elemental", 
       type1:  "common", 
       type2:  "hero", 
       class:  "construct", 
       personality:  "fearless", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  4, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  35,
       MaxNoOfFigs: -1, 
       NoOfFigs: 1
   }, 
   { 
       name: "estivara", 
       faction:  "utgar", 
       species:  "drow", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "arachnomancer", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  4, 
       life:  4, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  80,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "fen hydra", 
       faction:  "utgar", 
       species:  "hydra", 
       type1:  "uncommon", 
       type2:  "hero", 
       class:  "maraudar", 
       personality:  "ferocious", 
       size1:  "huge", 
       size2:  8, 
       life:  4, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  6, 
       cost:  120,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "fire elemental", 
       faction:  "utgar", 
       species:  "elemental", 
       type1:  "common", 
       type2:  "hero", 
       class:  "construct", 
       personality:  "mindless", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  35,
       MaxNoOfFigs: -1, 
       NoOfFigs: 1
   }, 
   { 
       name: "greater ice elemental", 
       faction:  "jandar", 
       species:  "elemental", 
       type1:  "uncommon", 
       type2:  "hero", 
       class:  "construct", 
       personality:  "dauntless", 
       size1:  "huge", 
       size2:  8, 
       life:  4, 
       move:  5, 
       range:  1, 
       attack:  6, 
       defense:  4, 
       cost:  130,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "greenscale warriors", 
       faction:  "ullar", 
       species:  "lizardfolk", 
       type1:  "common", 
       type2:  "squad", 
       class:  "warriors", 
       personality:  "loyal", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  2, 
       defense:  3, 
       cost:  60,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "mogrimm forgehammer", 
       faction:  "aquilla", 
       species:  "dwarf", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warlord", 
       personality:  "inspiring", 
       size1:  "medium", 
       size2:  4, 
       life:  6, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  2, 
       cost:  120,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "phantom knights", 
       faction:  "utgar", 
       species:  "undead", 
       type1:  "common", 
       type2:  "squad", 
       class:  "knights", 
       personality:  "tormented", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  4, 
       cost:  70,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "sahuagin raider", 
       faction:  "utgar", 
       species:  "sahuagin", 
       type1:  "common", 
       type2:  "hero", 
       class:  "raider", 
       personality:  "ferocious", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  2, 
       defense:  3, 
       cost:  25,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "sharwin wildborn", 
       faction:  "ullar", 
       species:  "eladrin", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "battle mage", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  6, 
       range:  1, 
       attack:  2, 
       defense:  3, 
       cost:  110,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "torin", 
       faction:  "utgar", 
       species:  "cyclops", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "hewer", 
       personality:  "terrifying", 
       size1:  "large", 
       size2:  7, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  120,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "water elemental", 
       faction:  "aquilla", 
       species:  "elemental", 
       type1:  "common", 
       type2:  "hero", 
       class:  "construct", 
       personality:  "resolute", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  4, 
       range:  5, 
       attack:  3, 
       defense:  4, 
       cost:  30,
       MaxNoOfFigs: -1, 
       NoOfFigs: 1
   }, 
   { 
       name: "wyvern", 
       faction:  "aquilla", 
       species:  "wyvern", 
       type1:  "uncommon", 
       type2:  "hero", 
       class:  "predator", 
       personality:  "ferocious", 
       size1:  "large", 
       size2:  7, 
       life:  4, 
       move:  7, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "acolarh", 
       faction:  "ullar", 
       species:  "elf", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "wizard", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  2, 
       cost:  110,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "hatamoto taro", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "samurai", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  2, 
       defense:  2, 
       cost:  130,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "laglor", 
       faction:  "vydar", 
       species:  "primadon", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "alphallon", 
       personality:  "precise", 
       size1:  "medium", 
       size2:  5, 
       life:  6, 
       move:  5, 
       range:  7, 
       attack:  3, 
       defense:  3, 
       cost:  110,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "ornak", 
       faction:  "utgar", 
       species:  "orc", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "champion", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  5, 
       life:  4, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "sir gilbert", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "champion", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  6, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  4, 
       cost:  105,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "the einar imperium", 
       faction:  "einar", 
       species:  "kyrie", 
       type1:  "common", 
       type2:  "squad", 
       class:  "soldiers", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  140,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "eldgrim the viking champion", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "champion", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  4, 
       life:  3, 
       move:  5, 
       range:  1, 
       attack:  2, 
       defense:  2, 
       cost:  30,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "empress kiova", 
       faction:  "einar", 
       species:  "kyrie", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warrior", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  6, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  4, 
       cost:  90,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
name: "heavy gruts", 
       faction:  "utgar", 
       species:  "orc", 
       type1:  "common", 
       type2:  "squad", 
       class:  "warriors", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  70,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "kaemon awa", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "samurai", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  4, 
       move:  5, 
       range:  7, 
       attack:  4, 
       defense:  4, 
       cost:  120,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "kee-mo-shi", 
       faction:  "utgar", 
       species:  "marro", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warwitch", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  6, 
       life:  4, 
       move:  6, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  130,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "runa", 
       faction:  "utgar", 
       species:  "kyrie", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warrior", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  120,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "shades of bleakewoode", 
       faction:  "utgar", 
       species:  "undead", 
       type1:  "common", 
       type2:  "squad", 
       class:  "devourers", 
       personality:  "terrifying", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  7, 
       range:  1, 
       attack:  2, 
       defense:  4, 
       cost:  100,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "tagawa samurai archers", 
       faction:  "einar", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "samurai", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  6, 
       attack:  2, 
       defense:  3, 
       cost:  65,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "zombies of morindan", 
       faction:  "utgar", 
       species:  "undead", 
       type1:  "common", 
       type2:  "squad", 
       class:  "savages", 
       personality:  "terrifying", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  4, 
       range:  1, 
       attack:  2, 
       defense:  3, 
       cost:  60,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "arkmer", 
       faction:  "ullar", 
       species:  "elf", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "wizard", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  3, 
       move:  5, 
       range:  5, 
       attack:  4, 
       defense:  2, 
       cost:  50,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "chardris", 
       faction:  "ullar", 
       species:  "elf", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "wizard", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  6, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  2, 
       cost:  90,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "emirroon", 
       faction:  "ullar", 
       species:  "elf", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "wizard", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  80,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "grok riders", 
       faction:  "utgar", 
       species:  "marro", 
       type1:  "common", 
       type2:  "squad", 
       class:  "hunters", 
       personality:  "menacing", 
       size1:  "large", 
       size2:  5, 
       life:  1, 
       move:  7, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  130,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "jorhdawn", 
       faction:  "ullar", 
       species:  "elf", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "wizard", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  4, 
       life:  6, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  2, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "kato katsuro", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "daimyo", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  6, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  200,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "moriko", 
       faction:  "ullar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "ninja", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  4, 
       life:  4, 
       move:  6, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  110,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "otonashi", 
       faction:  "vydar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "ninja", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  2, 
       defense:  3, 
       cost:  10,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "10th regiment of foot", 
       faction:  "einar", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "soldiers", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  6, 
       attack:  2, 
       defense:  2, 
       cost:  75,
       MaxNoOfFigs: -1, 
       NoOfFigs: 4
   }, 
   { 
       name: "sir dupuis", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "knight", 
       personality:  "valiant", 
       size1:  "large", 
       size2:  6, 
       life:  6, 
       move:  8, 
       range:  1, 
       attack:  4, 
       defense:  3, 
       cost:  150,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "ulginesh", 
       faction:  "ullar", 
       species:  "elf", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "wizard", 
       personality:  "tricky", 
       size1:  "large", 
       size2:  6, 
       life:  5, 
       move:  7, 
       range:  6, 
       attack:  3, 
       defense:  3, 
       cost:  150,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "wolves of badru", 
       faction:  "utgar", 
       species:  "wolves", 
       type1:  "common", 
       type2:  "squad", 
       class:  "hunters", 
       personality:  "relentless", 
       size1:  "small", 
       size2:  3, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  80,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "ashigaru harquebus", 
       faction:  "einar", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "ashigaru", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  6, 
       attack:  2, 
       defense:  1, 
       cost:  60,
       MaxNoOfFigs: -1, 
       NoOfFigs: 4
   }, 
   { 
       name: "ashigaru yari", 
       faction:  "einar", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "ashigaru", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  2, 
       defense:  1, 
       cost:  40,
       MaxNoOfFigs: -1, 
       NoOfFigs: 4
   }, 
   { 
       name: "cyprien esenwein", 
       faction:  "utgar", 
       species:  "undead", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "lord", 
       personality:  "terrifying", 
       size1:  "medium", 
       size2:  4, 
       life:  6, 
       move:  8, 
       range:  1, 
       attack:  3, 
       defense:  4, 
       cost:  150,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "isamu", 
       faction:  "utgar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "ninja", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  1, 
       cost:  10,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "iskra esenwein", 
       faction:  "utgar", 
       species:  "undead", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "duchess", 
       personality:  "terrifying", 
       size1:  "medium", 
       size2:  4, 
       life:  4, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  50,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "kyntela gwyn", 
       faction:  "ullar", 
       species:  "elf", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "wizard", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  4, 
       life:  2, 
       move:  5, 
       range:  1, 
       attack:  2, 
       defense:  2, 
       cost:  20,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "marcu esenwein", 
       faction:  "utgar", 
       species:  "undead", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "devourer", 
       personality:  "terrifying", 
       size1:  "medium", 
       size2:  4, 
       life:  6, 
       move:  7, 
       range:  1, 
       attack:  4, 
       defense:  1, 
       cost:  20,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "rechets of bogdan", 
       faction:  "utgar", 
       species:  "undead", 
       type1:  "unique", 
       type2:  "squad", 
       class:  "devourer", 
       personality:  "terrifying", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  50,
       MaxNoOfFigs: 3, 
       NoOfFigs: 3
   }, 
   { 
       name: "sonya esenwein", 
       faction:  "utgar", 
       species:  "undead", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "lady", 
       personality:  "terrifying", 
       size1:  "medium", 
       size2:  4, 
       life:  3, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  45,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "templar cavalry", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "knights", 
       personality:  "valiant", 
       size1:  "large", 
       size2:  6, 
       life:  1, 
       move:  8, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  120,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "warden 816", 
       faction:  "utgar", 
       species:  "soulborg", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warden", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  4, 
       life:  2, 
       move:  5, 
       range:  7, 
       attack:  3, 
       defense:  6, 
       cost:  90,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "alastair macdirk", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "champion", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  6, 
       move:  5, 
       range:  1, 
       attack:  5, 
       defense:  3, 
       cost:  110,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "concan", 
       faction:  "jandar", 
       species:  "kyrie", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warrior", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  80,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "deathwalker 7000", 
       faction:  "utgar", 
       species:  "soulbrog", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "deathwalker", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  7, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "gorillinators", 
       faction:  "vydar", 
       species:  "primadon", 
       type1:  "common", 
       type2:  "squad", 
       class:  "agents", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  7, 
       range:  6, 
       attack:  2, 
       defense:  1, 
       cost:  90,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "johnny \"shotgun\" sullivan", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "lawman", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  7, 
       attack:  2, 
       defense:  2, 
       cost:  65,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "macdirk warriors", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "warriors", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  2, 
       defense:  2, 
       cost:  80,
       MaxNoOfFigs: -1, 
       NoOfFigs: 4
   }, 
   { 
       name: "marrden hounds", 
       faction:  "utgar", 
       species:  "wulsinu", 
       type1:  "common", 
       type2:  "squad", 
       class:  "hunters", 
       personality:  "wild", 
       size1:  "large", 
       size2:  4, 
       life:  1, 
       move:  1, 
       range:  1, 
       attack:  3, 
       defense:  5, 
       cost:  90,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "microcorp agents", 
       faction:  "vydar", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "agents", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  7, 
       attack:  2, 
       defense:  3, 
       cost:  100,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "saylind the kyrie warrior", 
       faction:  "ullar", 
       species:  "kyrie", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warrior", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  80,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "sentinels of jandar", 
       faction:  "jandar", 
       species:  "kyrie", 
       type1:  "common", 
       type2:  "squad", 
       class:  "sentinels", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  4, 
       range:  1, 
       attack:  3, 
       defense:  4, 
       cost:  110,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "shaolin monks", 
       faction:  "ullar", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "monks", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  80,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "arrow gruts", 
       faction:  "utgar", 
       species:  "orc", 
       type1:  "common", 
       type2:  "squad", 
       class:  "archers", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  6, 
       range:  6, 
       attack:  1, 
       defense:  1, 
       cost:  40,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "blade gruts", 
       faction:  "utgar", 
       species:  "orc", 
       type1:  "common", 
       type2:  "squad", 
       class:  "warriors", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  2, 
       defense:  2, 
       cost:  40,
       MaxNoOfFigs: -1, 
       NoOfFigs: 4
   }, 
   { 
       name: "kelda the kyrie warrior", 
       faction:  "jandar", 
       species:  "kyrie", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warrior", 
       personality:  "merciful", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  6, 
       range:  1, 
       attack:  2, 
       defense:  3, 
       cost:  80,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "marcus decimus gallus", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warlord", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  6, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "omnicron snipers", 
       faction:  "jandar", 
       species:  "soulborg", 
       type1:  "common", 
       type2:  "squad", 
       class:  "snipers", 
       personality:  "precise", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  7, 
       attack:  1, 
       defense:  3, 
       cost:  100,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "roman archers", 
       faction:  "einar", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "archers", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  4, 
       range:  6, 
       attack:  2, 
       defense:  1, 
       cost:  55,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "roman legionnaires", 
       faction:  "einar", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "soldier", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  4, 
       range:  1, 
       attack:  3, 
       defense:  2, 
       cost:  50,
       MaxNoOfFigs: -1, 
       NoOfFigs: 4
   }, 
   { 
       name: "taelord the kyrie warrior", 
       faction:  "utgar", 
       species:  "kyrie", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warrior", 
       personality:  "relentless", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  180,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "tornak", 
       faction:  "utgar", 
       species:  "orc", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "champion", 
       personality:  "tricky", 
       size1:  "large", 
       size2:  6, 
       life:  3, 
       move:  7, 
       range:  1, 
       attack:  4, 
       defense:  5, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "venoc vipers", 
       faction:  "ullar", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "scouts", 
       personality:  "relentless", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  7, 
       range:  1, 
       attack:  3, 
       defense:  0, 
       cost:  40,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "venoc warlord", 
       faction:  "ullar", 
       species:  "viper", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warlord", 
       personality:  "relentless", 
       size1:  "medium", 
       size2:  6, 
       life:  6, 
       move:  7, 
       range:  1, 
       attack:  4, 
       defense:  3, 
       cost:  120,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "death chasers of thesk", 
       faction:  "valkrill", 
       species:  "orcs", 
       type1:  "common", 
       type2:  "squad", 
       class:  "hunters", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  2, 
       cost:  55,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "death knights of valkrill", 
       faction:  "valkrill", 
       species:  "undead", 
       type1:  "common", 
       type2:  "squad", 
       class:  "death knights", 
       personality:  "tormented", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  2, 
       defense:  5, 
       cost:  60,
       MaxNoOfFigs: -1, 
       NoOfFigs: 2
   }, 
   { 
       name: "eltahale", 
       faction:  "jandar", 
       species:  "goliath", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warden", 
       personality:  "fearless", 
       size1:  "medium", 
       size2:  5, 
       life:  6, 
       move:  6, 
       range:  1, 
       attack:  5, 
       defense:  4, 
       cost:  140,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "evar scarcarver", 
       faction:  "vydar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "frostrager", 
       personality:  "reckless", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  6, 
       range:  4, 
       attack:  2, 
       defense:  3, 
       cost:  110,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "frost giant of morh", 
       faction:  "utgar", 
       species:  "giant", 
       type1:  "uncommon", 
       type2:  "hero", 
       class:  "brute", 
       personality:  "fearless", 
       size1:  "huge", 
       size2:  9, 
       life:  6, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  140,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "ice troll berserker", 
       faction:  "utgar", 
       species:  "troll", 
       type1:  "uncommon", 
       type2:  "hero", 
       class:  "beast", 
       personality:  "ferocious", 
       size1:  "large", 
       size2:  5, 
       life:  4, 
       move:  5, 
       range:  1, 
       attack:  5, 
       defense:  2, 
       cost:  85,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "master of the hunt", 
       faction:  "einar", 
       species:  "firbolg", 
       type1:  "uncommon", 
       type2:  "hero", 
       class:  "hunter", 
       personality:  "bold", 
       size1:  "large", 
       size2:  6, 
       life:  6, 
       move:  6, 
       range:  4, 
       attack:  4, 
       defense:  4, 
       cost:  140,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "mezzodemon warmongers", 
       faction:  "valkrill", 
       species:  "deomns", 
       type1:  "common", 
       type2:  "squad", 
       class:  "warmongers", 
       personality:  "ferocious", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  4, 
       attack:  3, 
       defense:  3, 
       cost:  65,
       MaxNoOfFigs: -1, 
       NoOfFigs: 2
   }, 
   { 
       name: "moltenclaw", 
       faction:  "utgar", 
       species:  "dragon", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "prince", 
       personality:  "fearless", 
       size1:  "huge", 
       size2:  8, 
       life:  6, 
       move:  5, 
       range:  1, 
       attack:  5, 
       defense:  3, 
       cost:  170,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "ogre pulverizer", 
       faction:  "utgar", 
       species:  "ogre", 
       type1:  "uncommon", 
       type2:  "hero", 
       class:  "pulverizer", 
       personality:  "wild", 
       size1:  "large", 
       size2:  6, 
       life:  6, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  3, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "siege", 
       faction:  "vydar", 
       species:  "warforged", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "juggernaut", 
       personality:  "stoic", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  5, 
       defense:  5, 
       cost:  120,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "horned skull brutes", 
       faction:  "valkrill", 
       species:  "goblins", 
       type1:  "common", 
       type2:  "squad", 
       class:  "brutes", 
       personality:  "merciless", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  75,
       MaxNoOfFigs: -1, 
       NoOfFigs: 1
   }, 
   { 
       name: "brunak", 
       faction:  "utgar", 
       species:  "trolticor", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "mount", 
       personality:  "ferocious", 
       size1:  "huge", 
       size2:  8, 
       life:  3, 
       move:  6, 
       range:  1, 
       attack:  4, 
       defense:  7, 
       cost:  110,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "charos", 
       faction:  "ullar", 
       species:  "dragon", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "king", 
       personality:  "valiant", 
       size1:  "huge", 
       size2:  9, 
       life:  9, 
       move:  5, 
       range:  1, 
       attack:  5, 
       defense:  5, 
       cost:  210,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "deathwalker 8000", 
       faction:  "utgar", 
       species:  "soulborg", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "deathwalker", 
       personality:  "precise", 
       size1:  "large", 
       size2:  7, 
       life:  1, 
       move:  5, 
       range:  7, 
       attack:  3, 
       defense:  8, 
       cost:  130,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "dund", 
       faction:  "vydar", 
       species:  "doggin", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "hunter", 
       personality:  "tricky", 
       size1:  "large", 
       size2:  4, 
       life:  4, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  5, 
       cost:  110,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "su-bak-na", 
       faction:  "utgar", 
       species:  "marro", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "hivelord", 
       personality:  "tricky", 
       size1:  "huge", 
       size2:  12, 
       life:  5, 
       move:  6, 
       range:  1, 
       attack:  7, 
       defense:  3, 
       cost:  160,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "agent skahen", 
       faction:  "vydar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "agent", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  4, 
       life:  3, 
       move:  6, 
       range:  7, 
       attack:  3, 
       defense:  3, 
       cost:  120,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "master win chiu woo", 
       faction:  "aquilla", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "monk", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  140,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "samuel brown", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "patriot", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  4, 
       move:  5, 
       range:  7, 
       attack:  3, 
       defense:  3, 
       cost:  60,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "braxas", 
       faction:  "vydar", 
       species:  "dragon", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "queen", 
       personality:  "wild", 
       size1:  "huge", 
       size2:  13, 
       life:  8, 
       move:  6, 
       range:  1, 
       attack:  5, 
       defense:  3, 
       cost:  210,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "jotun", 
       faction:  "ullar", 
       species:  "giant", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warrior", 
       personality:  "wild", 
       size1:  "huge", 
       size2:  10, 
       life:  7, 
       move:  6, 
       range:  1, 
       attack:  8, 
       defense:  4, 
       cost:  225,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "major q9", 
       faction:  "vydar", 
       species:  "soulborg", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "major", 
       personality:  "precise", 
       size1:  "large", 
       size2:  7, 
       life:  4, 
       move:  5, 
       range:  8, 
       attack:  4, 
       defense:  7, 
       cost:  180,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "nilfheim", 
       faction:  "jandar", 
       species:  "dragon", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "king", 
       personality:  "ferocious", 
       size1:  "huge", 
       size2:  12, 
       life:  6, 
       move:  6, 
       range:  1, 
       attack:  6, 
       defense:  4, 
       cost:  185,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "theracus", 
       faction:  "ullar", 
       species:  "gryphillin", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "scout", 
       personality:  "disciplined", 
       size1:  "lage", 
       size2:  5, 
       life:  3, 
       move:  7, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  40,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "agent carr", 
       faction:  "vydar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "agent", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  4, 
       move:  5, 
       range:  1, 
       attack:  2, 
       defense:  4, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "airborne elite", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "squad", 
       class:  "soldiers", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  4, 
       range:  8, 
       attack:  3, 
       defense:  2, 
       cost:  110,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "deathwalker 9000", 
       faction:  "utgar", 
       species:  "soulborg", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "deathwalker", 
       personality:  "precise", 
       size1:  "large", 
       size2:  7, 
       life:  1, 
       move:  5, 
       range:  7, 
       attack:  4, 
       defense:  9, 
       cost:  140,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "finn the viking champion", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "champion", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  4, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  4, 
       cost:  80,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "grimnak", 
       faction:  "utgar", 
       species:  "orc", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "champion", 
       personality:  "ferocious", 
       size1:  "huge", 
       size2:  11, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  2, 
       defense:  4, 
       cost:  120,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "izumi samurai", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "squad", 
       class:  "samurai", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  2, 
       defense:  5, 
       cost:  60,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "krav maga agents", 
       faction:  "vydar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "squad", 
       class:  "agents", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  6, 
       range:  7, 
       attack:  3, 
       defense:  3, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "marro warriors", 
       faction:  "utgar", 
       species:  "marro", 
       type1:  "unique", 
       type2:  "squad", 
       class:  "warriors", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  6, 
       range:  6, 
       attack:  2, 
       defense:  3, 
       cost:  50,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "mimring", 
       faction:  "utgar", 
       species:  "dragon", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "beast", 
       personality:  "ferocious", 
       size1:  "huge", 
       size2:  9, 
       life:  5, 
       move:  6, 
       range:  1, 
       attack:  4, 
       defense:  3, 
       cost:  150,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "ne-gok-sa", 
       faction:  "utgar", 
       species:  "marro", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warlord", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  6, 
       cost:  90,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "raelin the kyrie warrior rotv", 
       faction:  "kyrie", 
       species:  "elf", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warrior", 
       personality:  "merciful", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  80,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "sgt. drake alexander rotv", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "soldier", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  6, 
       defense:  3, 
       cost:  110,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "syvarris", 
       faction:  "ullar", 
       species:  "elf", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "archer", 
       personality:  "precise", 
       size1:  "medium", 
       size2:  5, 
       life:  4, 
       move:  5, 
       range:  9, 
       attack:  3, 
       defense:  2, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "tarn viking warriors", 
       faction:  "jandar", 
       species:  "huamn", 
       type1:  "unique", 
       type2:  "squad", 
       class:  "warriors", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  4, 
       range:  1, 
       attack:  3, 
       defense:  4, 
       cost:  50,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "thorgrim the viking champion", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "champion", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  4, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  4, 
       cost:  80,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "zettian guards", 
       faction:  "utgar", 
       species:  "soulborg", 
       type1:  "unique", 
       type2:  "squad", 
       class:  "guards", 
       personality:  "precise", 
       size1:  "medium", 
       size2:  1, 
       life:  4, 
       move:  4, 
       range:  1, 
       attack:  2, 
       defense:  7, 
       cost:  70,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "dumutef guard", 
       faction:  "utgar", 
       species:  "fiantooth", 
       type1:  "common", 
       type2:  "hero", 
       class:  "guard", 
       personality:  "relentless", 
       size1:  "large", 
       size2:  7, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  25,
       MaxNoOfFigs: -1, 
       NoOfFigs: 1
   }, 
   { 
       name: "major q10", 
       faction:  "vydar", 
       species:  "soulborg", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "major", 
       personality:  "merciful", 
       size1:  "large", 
       size2:  6, 
       life:  4, 
       move:  5, 
       range:  8, 
       attack:  4, 
       defense:  5, 
       cost:  150,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "marrden nagrubs", 
       faction:  "utgar", 
       species:  "nagrubs", 
       type1:  "common", 
       type2:  "squad", 
       class:  "guards", 
       personality:  "loyal", 
       size1:  "small", 
       size2:  3, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  2, 
       defense:  2, 
       cost:  30,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "marro drudge", 
       faction:  "utgar", 
       species:  "marro", 
       type1:  "common", 
       type2:  "squad", 
       class:  "hunters", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  5, 
       range:  5, 
       attack:  2, 
       defense:  2, 
       cost:  50,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "marro hive", 
       faction:  "utgar", 
       species:  "marro", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "hive", 
       personality:  "terrifying", 
       size1:  "huge", 
       size2:  17, 
       life:  6, 
       move:  0, 
       range:  1, 
       attack:  0, 
       defense:  2, 
       cost:  160,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "marro stingers", 
       faction:  "utgar", 
       species:  "marro", 
       type1:  "common", 
       type2:  "squad", 
       class:  "stingers", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  5, 
       range:  5, 
       attack:  3, 
       defense:  3, 
       cost:  60,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "raelin the kyrie warrior sotm", 
       faction:  "jandar", 
       species:  "kyrie", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warrior", 
       personality:  "resolute", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  120,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "sgt. drake alexander sotm", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "soldier", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  6, 
       move:  6, 
       range:  1, 
       attack:  6, 
       defense:  4, 
       cost:  170,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "shiori", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "ninja", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  4, 
       life:  3, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  60,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "sonlen", 
       faction:  "ullar", 
       species:  "elf", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "archmage", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  6, 
       move:  5, 
       range:  6, 
       attack:  4, 
       defense:  3, 
       cost:  160,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "tor-kul-na", 
       faction:  "utgar", 
       species:  "marro", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "hivelord", 
       personality:  "terrifying", 
       size1:  "huge", 
       size2:  11, 
       life:  6, 
       move:  6, 
       range:  1, 
       attack:  6, 
       defense:  5, 
       cost:  220,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "dzu-teh", 
       faction:  "jandar", 
       species:  "dzu-teh", 
       type1:  "common", 
       type2:  "squad", 
       class:  "hunters", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  6, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  3, 
       cost:  75,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "abomination", 
       faction:  "marvel", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "creature", 
       personality:  "ferocious", 
       size1:  "medium", 
       size2:  6, 
       life:  8, 
       move:  5, 
       range:  1, 
       attack:  7, 
       defense:  6, 
       cost:  320,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "captain america", 
       faction:  "marvel", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "soldier", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  6, 
       defense:  6, 
       cost:  220,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "doctor doom", 
       faction:  "marvel", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "ruler", 
       personality:  "egomaniacal", 
       size1:  "medium", 
       size2:  5, 
       life:  4, 
       move:  6, 
       range:  6, 
       attack:  5, 
       defense:  6, 
       cost:  245,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "incredible hulk", 
       faction:  "marvel", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "creature", 
       personality:  "angry", 
       size1:  "medium", 
       size2:  6, 
       life:  8, 
       move:  5, 
       range:  1, 
       attack:  6, 
       defense:  6, 
       cost:  370,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "iron man", 
       faction:  "marvel", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "adventurer", 
       personality:  "arrogant", 
       size1:  "medium", 
       size2:  5, 
       life:  4, 
       move:  6, 
       range:  6, 
       attack:  4, 
       defense:  6, 
       cost:  240,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "red skull", 
       faction:  "marvel", 
       species:  "clone", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "mastermind", 
       personality:  "ruthless", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  5, 
       attack:  4, 
       defense:  3, 
       cost:  190,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "silver surfer", 
       faction:  "marvel", 
       species:  "zenn-lavian", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "herald", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  6, 
       move:  6, 
       range:  4, 
       attack:  4, 
       defense:  7, 
       cost:  320,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "spider-man", 
       faction:  "marvel", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "crime fighter", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  6, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  160,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "thanos", 
       faction:  "marvel", 
       species:  "eternal", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "conqueror", 
       personality:  "nihilist", 
       size1:  "medium", 
       size2:  5, 
       life:  6, 
       move:  6, 
       range:  6, 
       attack:  6, 
       defense:  7, 
       cost:  360,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "venom", 
       faction:  "marvel", 
       species:  "symbiote", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "vigilante", 
       personality:  "ferocious", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  6, 
       range:  1, 
       attack:  6, 
       defense:  4, 
       cost:  150,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "blastatrons", 
       faction:  "vydar", 
       species:  "soulborg", 
       type1:  "common", 
       type2:  "squad", 
       class:  "guards", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  5, 
       range:  7, 
       attack:  1, 
       defense:  2, 
       cost:  60,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "crixus", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "gladiator", 
       personality:  "rebellious", 
       size1:  "medium", 
       size2:  4, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  5, 
       defense:  3, 
       cost:  90,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "deathreavers", 
       faction:  "utgar", 
       species:  "soulborg", 
       type1:  "common", 
       type2:  "squad", 
       class:  "deathreavers", 
       personality:  "tricky", 
       size1:  "small", 
       size2:  3, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  1, 
       defense:  4, 
       cost:  40,
       MaxNoOfFigs: -1, 
       NoOfFigs: 4
   }, 
   { 
       name: "deathstalkers", 
       faction:  "utgar", 
       species:  "soulborg", 
       type1:  "common", 
       type2:  "squad", 
       class:  "deathstalkers", 
       personality:  "wild", 
       size1:  "large", 
       size2:  5, 
       life:  1, 
       move:  7, 
       range:  1, 
       attack:  3, 
       defense:  5, 
       cost:  100,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "kozuke samurai", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "squad", 
       class:  "samurai", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  5, 
       defense:  3, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "nakita agents", 
       faction:  "vydar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "squad", 
       class:  "agents", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  5, 
       range:  6, 
       attack:  3, 
       defense:  3, 
       cost:  120,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "ninjas of the northern wind", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "squad", 
       class:  "ninja", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  4, 
       defense:  3, 
       cost:  110,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "retiarius", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "gladiator", 
       personality:  "rebellious", 
       size1:  "medium", 
       size2:  5, 
       life:  4, 
       move:  5, 
       range:  1, 
       attack:  5, 
       defense:  3, 
       cost:  90,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "spartacus", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "gladiator", 
       personality:  "rebellious", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  6, 
       defense:  4, 
       cost:  200,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "warriors of ashra", 
       faction:  "ullar", 
       species:  "elves", 
       type1:  "common", 
       type2:  "squad", 
       class:  "warrior", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  50,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "fyorlag spiders", 
       faction:  "aquilla", 
       species:  "arachnids", 
       type1:  "common", 
       type2:  "squad", 
       class:  "scouts", 
       personality:  "wild", 
       size1:  "small", 
       size2:  2, 
       life:  1, 
       move:  7, 
       range:  1, 
       attack:  2, 
       defense:  2, 
       cost:  40,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "anubian wolves", 
       faction:  "utgar", 
       species:  "wolves", 
       type1:  "common", 
       type2:  "squad", 
       class:  "devourers", 
       personality:  "relentless", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  1, 
       defense:  4, 
       cost:  75,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "khosumet the darklord", 
       faction:  "utgar", 
       species:  "wolf", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "darklord", 
       personality:  "relentless", 
       size1:  "medium", 
       size2:  5, 
       life:  3, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  75,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "knights of weston", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "knights", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  4, 
       range:  1, 
       attack:  3, 
       defense:  4, 
       cost:  70,
       MaxNoOfFigs: -1, 
       NoOfFigs: 4
   }, 
   { 
       name: "krug", 
       faction:  "utgar", 
       species:  "troll", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "beast", 
       personality:  "relentless", 
       size1:  "huge", 
       size2:  8, 
       life:  8, 
       move:  5, 
       range:  1, 
       attack:  2, 
       defense:  3, 
       cost:  120,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "marro drones", 
       faction:  "utgar", 
       species:  "marro", 
       type1:  "common", 
       type2:  "squad", 
       class:  "drones", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  50,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "4th massachusetts line", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "soldiers", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  6, 
       attack:  2, 
       defense:  2, 
       cost:  70,
       MaxNoOfFigs: -1, 
       NoOfFigs: 4
   }, 
   { 
       name: "me-burq-Sa", 
       faction:  "utgar", 
       species:  "marro", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warlord", 
       personality:  "wild", 
       size1:  "large", 
       size2:  7, 
       life:  3, 
       move:  8, 
       range:  6, 
       attack:  3, 
       defense:  3, 
       cost:  50,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "minions of utgar", 
       faction:  "utgar", 
       species:  "kyrie", 
       type1:  "common", 
       type2:  "squad", 
       class:  "minions", 
       personality:  "relentless", 
       size1:  "medium", 
       size2:  6, 
       life:  1, 
       move:  4, 
       range:  1, 
       attack:  2, 
       defense:  6, 
       cost:  110,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "sir denrick", 
       faction:  "jandar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "champion", 
       personality:  "valiant", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "swog rider", 
       faction:  "utgar", 
       species:  "orc", 
       type1:  "common", 
       type2:  "hero", 
       class:  "beast", 
       personality:  "wild", 
       size1:  "large", 
       size2:  6, 
       life:  1, 
       move:  8, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  25,
       MaxNoOfFigs: -1, 
       NoOfFigs: 1
   }, 
   { 
       name: "elite onyx vipers", 
       faction:  "ullar", 
       species:  "vipers", 
       type1:  "unique", 
       type2:  "squad", 
       class:  "scout", 
       personality:  "precise", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  7, 
       range:  1, 
       attack:  3, 
       defense:  2, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "granite guardians", 
       faction:  "aquilla", 
       species:  "elementars", 
       type1:  "common", 
       type2:  "squad", 
       class:  "guards", 
       personality:  "dauntless", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  3, 
       range:  1, 
       attack:  3, 
       defense:  5, 
       cost:  100,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "nerak the glacian swog rider", 
       faction:  "utgar", 
       species:  "orc", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "champion", 
       personality:  "wild", 
       size1:  "large", 
       size2:  6, 
       life:  3, 
       move:  8, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  50,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "quasatch hunters", 
       faction:  "aquilla", 
       species:  "quasatch", 
       type1:  "common", 
       type2:  "squad", 
       class:  "hunters", 
       personality:  "ferocious", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  4, 
       cost:  100,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "sir hawthorne", 
       faction:  "utgar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "champion", 
       personality:  "relentless", 
       size1:  "medium", 
       size2:  5, 
       life:  6, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  90,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "obsidian guards", 
       faction:  "utgar", 
       species:  "moltarn", 
       type1:  "common", 
       type2:  "squad", 
       class:  "guards", 
       personality:  "ferocious", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  4, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  100,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "black wyrmling", 
       faction:  "vydar", 
       species:  "dragon", 
       type1:  "common", 
       type2:  "hero", 
       class:  "wyrmling", 
       personality:  "wild", 
       size1:  "small", 
       size2:  3, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  30,
       MaxNoOfFigs: -1, 
       NoOfFigs: 1
   }, 
   { 
       name: "blue wyrmling", 
       faction:  "aquilla", 
       species:  "dragon", 
       type1:  "common", 
       type2:  "hero", 
       class:  "wyrmling", 
       personality:  "precise", 
       size1:  "small", 
       size2:  3, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  3, 
       cost:  35,
       MaxNoOfFigs: -1, 
       NoOfFigs: 1
   }, 
   { 
       name: "goblin cutters", 
       faction:  "utgar", 
       species:  "goblins", 
       type1:  "common", 
       type2:  "squad", 
       class:  "cutters", 
       personality:  "skittish", 
       size1:  "small", 
       size2:  3, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  2, 
       defense:  1, 
       cost:  50,
       MaxNoOfFigs: -1, 
       NoOfFigs: 4
   }, 
   { 
       name: "heirloom", 
       faction:  "vydar", 
       species:  "warforged", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "wizard", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  4, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  2, 
       cost:  90,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "iron golem", 
       faction:  "vydar", 
       species:  "golem", 
       type1:  "uncommon", 
       type2:  "hero", 
       class:  "construct", 
       personality:  "mindless", 
       size1:  "large", 
       size2:  7, 
       life:  3, 
       move:  5, 
       range:  1, 
       attack:  6, 
       defense:  6, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "kurrok the elementalist", 
       faction:  "utgar", 
       species:  "hobgoblin", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "sorcerer", 
       personality:  "devout", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  120,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "mika connour", 
       faction:  "vydar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "shadow assassin", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  6, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  110,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "mind flayer mastermind", 
       faction:  "utgar", 
       species:  "mind flayer", 
       type1:  "uncommon", 
       type2:  "hero", 
       class:  "psychic", 
       personality:  "terrifying", 
       size1:  "medium", 
       size2:  5, 
       life:  4, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "ogre warhulk", 
       faction:  "utgar", 
       species:  "ogre", 
       type1:  "uncommon", 
       type2:  "hero", 
       class:  "warhulk", 
       personality:  "wild", 
       size1:  "large", 
       size2:  7, 
       life:  8, 
       move:  5, 
       range:  1, 
       attack:  5, 
       defense:  3, 
       cost:  150,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "red wyrmling", 
       faction:  "einar", 
       species:  "dragon", 
       type1:  "common", 
       type2:  "hero", 
       class:  "wyrmling", 
       personality:  "disciplined", 
       size1:  "small", 
       size2:  3, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  30,
       MaxNoOfFigs: -1, 
       NoOfFigs: 1
   }, 
   { 
       name: "rhogar dragonspine", 
       faction:  "aquilla", 
       species:  "dragonborn", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "paladin", 
       personality:  "ferocious", 
       size1:  "medium", 
       size2:  5, 
       life:  6, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  110,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "shurrak", 
       faction:  "utgar", 
       species:  "giant", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warrior", 
       personality:  "militaristic", 
       size1:  "huge", 
       size2:  8, 
       life:  6, 
       move:  6, 
       range:  1, 
       attack:  5, 
       defense:  4, 
       cost:  160,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "warforged soldiers", 
       faction:  "vydar", 
       species:  "warforged", 
       type1:  "common", 
       type2:  "squad", 
       class:  "soldiers", 
       personality:  "loyal", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  2, 
       cost:  80,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "werewolf lord", 
       faction:  "utgar", 
       species:  "lycanthrope", 
       type1:  "uncommon", 
       type2:  "hero", 
       class:  "darklord", 
       personality:  "relentless", 
       size1:  "huge", 
       size2:  9, 
       life:  6, 
       move:  6, 
       range:  1, 
       attack:  4, 
       defense:  4, 
       cost:  140,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "white wyrmling", 
       faction:  "jandar", 
       species:  "dragon", 
       type1:  "common", 
       type2:  "hero", 
       class:  "wyrmling", 
       personality:  "ferocious", 
       size1:  "small", 
       size2:  3, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  4, 
       cost:  30,
       MaxNoOfFigs: -1, 
       NoOfFigs: 1
   }, 
   { 
       name: "armoc vipers", 
       faction:  "ullar", 
       species:  "vipers", 
       type1:  "common", 
       type2:  "squad", 
       class:  "protectors", 
       personality:  "relentless", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  7, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  65,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "aubrien archers", 
       faction:  "ullar", 
       species:  "elf", 
       type1:  "common", 
       type2:  "squad", 
       class:  "archers", 
       personality:  "precise", 
       size1:  "medium", 
       size2:  4, 
       life:  1, 
       move:  5, 
       range:  7, 
       attack:  2, 
       defense:  2, 
       cost:  70,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "deadeye dan", 
       faction:  "ullar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "sniper", 
       personality:  "precise", 
       size1:  "medium", 
       size2:  5, 
       life:  3, 
       move:  5, 
       range:  10, 
       attack:  1, 
       defense:  2, 
       cost:  60,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "gladiatrons", 
       faction:  "vydar", 
       species:  "soulborg", 
       type1:  "common", 
       type2:  "squad", 
       class:  "hunters", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  5, 
       range:  1, 
       attack:  2, 
       defense:  3, 
       cost:  80,
       MaxNoOfFigs: -1, 
       NoOfFigs: 3
   }, 
   { 
       name: "guilty mccreech", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "lawman", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  4, 
       life:  2, 
       move:  5, 
       range:  7, 
       attack:  2, 
       defense:  2, 
       cost:  30,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "james murphy", 
       faction:  "vydar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "lawman", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  4, 
       life:  5, 
       move:  5, 
       range:  7, 
       attack:  2, 
       defense:  2, 
       cost:  75,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "major x17", 
       faction:  "vydar", 
       species:  "soulborg", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "major", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  4, 
       defense:  3, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "morsbane", 
       faction:  "ullar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "wizard", 
       personality:  "tricky", 
       size1:  "medium", 
       size2:  5, 
       life:  6, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  2, 
       cost:  100,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "parmenio", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warlord", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  5, 
       move:  5, 
       range:  1, 
       attack:  3, 
       defense:  3, 
       cost:  90,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "sacred band", 
       faction:  "einar", 
       species:  "human", 
       type1:  "common", 
       type2:  "squad", 
       class:  "soldiers", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  4, 
       range:  1, 
       attack:  3, 
       defense:  2, 
       cost:  50,
       MaxNoOfFigs: -1, 
       NoOfFigs: 4
   }, 
   { 
       name: "sudema", 
       faction:  "vydar", 
       species:  "undead", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "queen", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  5, 
       life:  4, 
       move:  5, 
       range:  1, 
       attack:  2, 
       defense:  3, 
       cost:  140,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "tagawa samurai", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "squad", 
       class:  "samurai", 
       personality:  "disciplined", 
       size1:  "medium", 
       size2:  5, 
       life:  1, 
       move:  6, 
       range:  1, 
       attack:  3, 
       defense:  5, 
       cost:  120,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
   { 
       name: "valguard", 
       faction:  "einar", 
       species:  "human", 
       type1:  "unique", 
       type2:  "hero", 
       class:  "warlord", 
       personality:  "wild", 
       size1:  "medium", 
       size2:  5, 
       life:  7, 
       move:  5, 
       range:  1, 
       attack:  2, 
       defense:  4, 
       cost:  110,
       MaxNoOfFigs: 1, 
       NoOfFigs: 1
   }, 
]; 
